[package]
authors = ["Mitchell R. Vollger <mrvollger@gmail.com>"]
build = "build.rs"
categories = ["command-line-utilities"]
description = "Fiber-seq toolkit in rust"
edition = "2021"
homepage = "https://fiberseq.github.io/fibertools-rs/"
keywords = ["cli", "bam", "bfx"]
license = "MIT"
name = "fibertools-rs"
readme = "README.md"
repository = "https://github.com/fiberseq/fibertools-rs"
version = "0.2.6"

[[bin]]
name = "ft"
path = "src/main.rs"

[dependencies]
anstyle = "1.0.0"
anyhow = "1.0.58"
bamlift = {path = "bamlift"}
bio = "1.2.0"
bio-io = {path = "bio-io"}
clap = {version = "4.3.4", features = ["cargo", "wrap_help", "color", "unstable-styles", "derive"], optional = true}
clap_complete = {version = "4.0.6", optional = true}
clap_mangen = {version = "0.2.5", optional = true}
colored = "2.0.0"
console = {version = "0.15", optional = true}
env_logger = "0.9.0"
gbdt = {version = "0.1.1", optional = true}
indicatif = {version = "0.17.0", features = ["rayon"]}
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4"
ordered-float = "3.4.0"
rayon = "1.5"
regex = "1.9.1"
rust-htslib = "0.44.1"
serde = {version = "1.0.104", features = ["derive"], optional = true}
serde_json = {version = "1.0.48", optional = true}
spin = "0.9.8"
tch = {version = "0.13.0", optional = true}
tempfile = "3.3.0"

[features]
cli = ["dep:clap", "dep:clap_complete", "dep:clap_mangen", "dep:console"]
default = ["predict", "cli"]
predict = ["dep:tch", "dep:gbdt", "dep:serde", "dep:serde_json"]

# generated by 'cargo dist init'
[profile.dist]
debug = true
inherits = "release"
split-debuginfo = "packed"

#[build-dependencies]
#burn-import = "0.7.0"

[dev-dependencies]
assert_cmd = "2.0.11"
predicates = "3.0.3"

[profile.dev]
opt-level = 2

[profile.release]
codegen-units = 1
debug = true
lto = "thin"
